/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cloud_logic_custom": [
        {
            "name": "podcasts",
            "endpoint": "https://s48gsu40c4.execute-api.us-east-2.amazonaws.com/dev",
            "region": "us-east-2"
        },
        {
            "name": "gamesapi",
            "endpoint": "https://8rkhi1lb26.execute-api.us-east-2.amazonaws.com/dev",
            "region": "us-east-2"
        },
        {
            "name": "decksapi",
            "endpoint": "https://jfh5t03ub6.execute-api.us-east-2.amazonaws.com/dev",
            "region": "us-east-2"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-2:54d71666-7634-4af4-a4bf-611670c2b22d",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_HXcLlxhsA",
    "aws_user_pools_web_client_id": "2vvf5olvutn3vpe7vhbkr4i66p",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_dynamodb_all_tables_region": "us-east-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "hs-gamesdb-dev",
            "region": "us-east-2"
        },
        {
            "tableName": "hs-decksdb-dev",
            "region": "us-east-2"
        }
    ]
};


export default awsmobile;
